# Generated by Django 5.1.3 on 2025-06-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="tags",
            field=models.ManyToManyField(
                related_name="projetos", through="projeto.ProjetoTag", to="projeto.tag"
            ),
        ),
    ]
