# Generated by Django 5.1.3 on 2025-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0002_projeto_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos",
                through="projeto.ProjetoTag",
                to="projeto.tag",
            ),
        ),
    ]
