# Generated by Django 5.1.3 on 2025-06-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0003_alter_projeto_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("autor", "Autor"),
                            ("orientador", "Orientador"),
                            ("colaborador", "Colaborador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Equipe",
                "verbose_name_plural": "Membros da Equipe",
                "unique_together": {("membro", "projeto")},
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_participados",
                through="projeto.Equipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
