# Generated by Django 5.1.3 on 2025-06-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0004_equipe_projeto_membros"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projetotag",
            options={
                "verbose_name": "Projeto Tag",
                "verbose_name_plural": "Projetos Tags",
            },
        ),
    ]
