# Generated by Django 5.1.3 on 2025-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_equipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="add_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aluno", "Aluno"),
                    ("orientador", "Orientador"),
                    ("avaliador", "Avaliador"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
