# Generated by Django 5.1.3 on 2025-06-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_add_em_alter_usuario_cpf_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Equipe",
        ),
    ]
